<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.0</TargetFramework>
    <Nullable>disable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Kcp" Version="2.7.0" />
    <PackageReference Include="MessagePack" Version="2.5.187" />
    <PackageReference Include="System.Text.Json" Version="6.0.10" />
  </ItemGroup>

</Project>
